### ISSUE TITLE
Exporting with error 'Image' object has no attribute 'use_clamp_x'.

### ISSUE THREAD

**Issue by CorallusCaninus** [niftools/blender_nif_plugin#371]
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
When exporting a mesh the plugin reports following error: AttributeError: 'Image' object has no attribute 'use_clamp_x'. This happens when trying to export with following Niftools Scene Panel Settings:
Setting the Game to Skyrim and leaving User Version / Version 2 at 12 / 83,
Setting the Game to Fallout3 and setting User Version / Version 2 to 11 / 34,
only setting Game to Oblivion and User Version / Version 2 to 11 / 11 seems to work.

 
### Blender Nif Plugin Version Info
2.6.0.dev4.b2-80-2020-05-27

### Blender Version Info
Blender 2.83

### Platform information
Windows 10 Pro 1809

## Steps to Reproduce
Loading the blend file and try to export the mesh.

## Expected Result
Exporting the mesh succeeded.

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 159, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\nif_export.py", line 172, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 112, in export_root_node
    n_root = self.export_node(b_obj, None)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 218, in export_node
    self.export_children(b_obj, node)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 233, in export_children
    self.export_node(b_child, n_parent)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\object\__init__.py", line 186, in export_node
    return self.mesh_helper.export_tri_shapes(b_obj, n_parent, b_obj.name)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\geometry\mesh\__init__.py", line 164, in export_tri_shapes
    self.object_property.export_properties(b_obj, b_mat, trishape)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\property\object\__init__.py", line 83, in export_properties
    bsshader = self.bss_helper.export_bs_shader_property(b_mat)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\property\shader\__init__.py", line 63, in export_bs_shader_property
    bsshader = self.export_bs_lighting_shader_property(b_mat)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\property\shader\__init__.py", line 99, in export_bs_lighting_shader_property
    self.texturehelper.export_bs_lighting_shader_prop_textures(bsshader)
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_nif\modules\nif_export\property\texture\types\bsshadertexture.py", line 99, in export_bs_lighting_shader_prop_textures
    if not b_img.use_clamp_x:
AttributeError: 'Image' object has no attribute 'use_clamp_x'

location: <unknown location>:-1

location: <unknown location>:-1

### Blend File
[Treepineforrest01.zip](https://github.com/niftools/blender_nif_plugin/files/4810221/Treepineforrest01.zip)

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by JimScript** [comment]
Well I Know I am not the guy who is working on this, but I was curious too, and found it is due to an API change from Blender 2.79 to 2.80. You see "use_clamp_x" was a Blender function that disabled texture repeating, as seen here "[2.75.3](https://docs.blender.org/api/blender_python_api_2_75_3/bpy.types.Image.html)", But it was removed as of 2.80, as seen here "[2.80 API Changelog](https://docs.blender.org/api/current/change_log.html?highlight=use_clamp_x)". With no known alternative, I don't know how to fix it, but at least we can under stand the problem better.

**Comment by CorallusCaninus** [comment]
Hi thanks for your findings, I am no programmer but commented out the lines in the bsshadertexture.py file under # Texture Clamping mode. But another error occurs in the __init__.py located in the nif_export\property\shader folder that the bsshader.skin_tint_color.r = b_mat.diffuse_color.r has no attribute .r. Since I want to finish the mod I am working on I will stick to 2.79 for the time being.
Anyhow, thanks again and thanks to all the people working on this.
